/* =========== LIMPIEZA DE BASE DE DATOS EN CASO DE EXISTIR =========== */
DROP DATABASE IF EXISTS DB_COMPUTERS_INVENTORY;

/* =========== CREACION BASE DE DATOS =========== */
CREATE DATABASE DB_COMPUTERS_INVENTORY;
USE DB_COMPUTERS_INVENTORY;

/* =========== CREACION DE OBJETOS Y RELACIONES =========== */

DROP TABLE IF EXISTS COMPUTADOR;
CREATE TABLE COMPUTADOR(
ID_PC INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
MARCA_PC VARCHAR (15) NOT NULL,
MODELO_PC VARCHAR (15) NOT NULL,
SERIAL_PC VARCHAR (20) NOT NULL UNIQUE,
PROCESADOR_PC VARCHAR (20) NOT NULL,
RAM_PC INT (3) NOT NULL,
UNIDAD_RAM_PC CHAR (2) NOT NULL,
ALMACENAMIENTO_PC INT (3) NOT NULL,
UNIDAD_ALMACENAMIENTO_PC CHAR (2) NOT NULL,
TIPO_SISTEMA_PC INT (2) NOT NULL,
SISTEMA_OPERATIVO_PC VARCHAR (10) NOT NULL,
VERSION_SO_PC VARCHAR (7) NOT NULL,
DISPONIBILIDAD_PC CHAR(13) NOT NULL,
ESTADO VARCHAR (8) NOT NULL,
CREATED_AT DATETIME NOT NULL,
UPDATED_AT DATETIME NOT NULL
);

DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA(
ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
RAZON_SOCIAL_EMPRESA VARCHAR (50) NOT NULL,
NIT_EMPRESA INT (9) NOT NULL UNIQUE,
DIRECCION_EMPRESA VARCHAR (50) NOT NULL,
CODIGO_POSTAL_EMPRESA INT (6) NOT NULL,
ESTADO VARCHAR (8) NOT NULL,
CREATED_AT DATETIME NOT NULL,
UPDATED_AT DATETIME NOT NULL
);

DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO(
ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_EMPRESA_FK INT,
NOMBRE_COMPLETO_EMPLEADO VARCHAR (70) NOT NULL,
CORREO_EMPLEADO VARCHAR (30) NOT NULL UNIQUE,
TIPO_DOCUMENTO_EMPLEADO VARCHAR (2) NOT NULL,
NUMERO_DOCUMENTO_EMPLEADO INT (10) NOT NULL UNIQUE ,
FECHA_NACIMIENTO_EMPLEADO DATE NOT NULL,
NUMERO_CELULAR_EMPLEADO CHAR (10) NOT NULL UNIQUE,
NUMERO_FIJO_EMPLEADO VARCHAR (7),
ESTADO VARCHAR (8) NOT NULL,
CREATED_AT DATETIME NOT NULL,
UPDATED_AT DATETIME NOT NULL
);

DROP TABLE IF EXISTS PRESTAMO;
CREATE TABLE PRESTAMO(
ID_PRESTAMO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_EMPLEADO_FK INT,
ID_PC_FK INT,
FECHA_INICIO_PRESTAMO DATETIME NOT NULL,
FECHA_FIN_PRESTAMO DATETIME NOT NULL,
ESTADO VARCHAR (8) NOT NULL,
CREATED_AT DATETIME NOT NULL,
UPDATED_AT DATETIME NOT NULL
);

/* =========== ALTER TABLES =========== */

ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_EMPRESA_FK) REFERENCES EMPRESA (ID_EMPRESA);
ALTER TABLE PRESTAMO ADD FOREIGN KEY (ID_EMPLEADO_FK) REFERENCES EMPLEADO (ID_EMPLEADO);
ALTER TABLE PRESTAMO ADD FOREIGN KEY (ID_PC_FK) REFERENCES COMPUTADOR (ID_PC);

/* =========== INSERCIONES =========== */

/* =========== EMPRESAS =========== */
INSERT INTO `empresa` (`ID_EMPRESA`, `RAZON_SOCIAL_EMPRESA`, `NIT_EMPRESA`, `DIRECCION_EMPRESA`, `CODIGO_POSTAL_EMPRESA`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'COMPAQ', '111999333', 'Cra. 44b #22-23', '1113','ACTIVO', '2021-12-27 22:31:00', '2021-12-27 22:31:00');
INSERT INTO `empresa` (`ID_EMPRESA`, `RAZON_SOCIAL_EMPRESA`, `NIT_EMPRESA`, `DIRECCION_EMPRESA`, `CODIGO_POSTAL_EMPRESA`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'SONY', '123123123', 'KR 20 #22 sur ', '123456','ACTIVO', '2021-12-27 10:53:39', '2021-12-27 10:53:39');
INSERT INTO `empresa` (`ID_EMPRESA`, `RAZON_SOCIAL_EMPRESA`, `NIT_EMPRESA`, `DIRECCION_EMPRESA`, `CODIGO_POSTAL_EMPRESA`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'Apple', '123333444', '123 kr 10', '444444','ACTIVO', '2021-12-28 02:17:00', '2021-12-28 02:17:00');
INSERT INTO `empresa` (`ID_EMPRESA`, `RAZON_SOCIAL_EMPRESA`, `NIT_EMPRESA`, `DIRECCION_EMPRESA`, `CODIGO_POSTAL_EMPRESA`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'Challenger', '2147483647', 'K10 # 11 - 07', '323254', 'ACTIVO', '2022-01-20 04:46:30', '2022-01-20 04:46:30');

SELECT * FROM EMPRESA;
SELECT ID_EMPRESA,RAZON_SOCIAL_EMPRESA FROM EMPRESA;

/* =========== COMPUTADORES =========== */

INSERT INTO `computador` (`ID_PC`, `MARCA_PC`, `MODELO_PC`, `SERIAL_PC`, `PROCESADOR_PC`, `RAM_PC`, `UNIDAD_RAM_PC`, `ALMACENAMIENTO_PC`, `UNIDAD_ALMACENAMIENTO_PC`, `TIPO_SISTEMA_PC`, `SISTEMA_OPERATIVO_PC`, `VERSION_SO_PC`, `DISPONIBILIDAD_PC`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'SAMSUNG', 'NOVA 4', 'GH44897K', 'INTEL i7', '16', 'Gb', '8', 'Tb', '64', 'LINUX', '3FF', 'Asignado','ACTIVO', '2021-12-28 00:00:00', '2021-12-28 00:00:00');
INSERT INTO `computador` (`ID_PC`, `MARCA_PC`, `MODELO_PC`, `SERIAL_PC`, `PROCESADOR_PC`, `RAM_PC`, `UNIDAD_RAM_PC`, `ALMACENAMIENTO_PC`, `UNIDAD_ALMACENAMIENTO_PC`, `TIPO_SISTEMA_PC`, `SISTEMA_OPERATIVO_PC`, `VERSION_SO_PC`, `DISPONIBILIDAD_PC`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'ASUS', 'ROG7K', '667JK9X', 'R 9 9550X', '32', 'Gb', '1', 'Tb', '64', 'WINDOWS 10', '45BH6', 'Disponible','ACTIVO', '2021-12-28 01:06:26', '2021-12-28 01:06:26');
INSERT INTO `computador` (`ID_PC`, `MARCA_PC`, `MODELO_PC`, `SERIAL_PC`, `PROCESADOR_PC`, `RAM_PC`, `UNIDAD_RAM_PC`, `ALMACENAMIENTO_PC`, `UNIDAD_ALMACENAMIENTO_PC`, `TIPO_SISTEMA_PC`, `SISTEMA_OPERATIVO_PC`, `VERSION_SO_PC`, `DISPONIBILIDAD_PC`,`ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'ASUS', 'ROG7K', '667JK9)', 'R 9 9550X', '32', 'Gb', '500', 'Gb', '64', 'WINDOWS 10', '45BH6', 'Mantenimiento','ACTIVO', '2021-12-28 01:06:26', '2021-12-28 01:06:26');
INSERT INTO `computador` (`ID_PC`, `MARCA_PC`, `MODELO_PC`, `SERIAL_PC`, `PROCESADOR_PC`, `RAM_PC`, `UNIDAD_RAM_PC`, `ALMACENAMIENTO_PC`, `UNIDAD_ALMACENAMIENTO_PC`, `TIPO_SISTEMA_PC`, `SISTEMA_OPERATIVO_PC`, `VERSION_SO_PC`, `DISPONIBILIDAD_PC`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, 'Huawei', 'Note Book 23', 'SH58869JK', 'Threadripper 5990x', '64', 'Gb', '16', 'Tb', '64', 'WINDOWS 11', 'HA778S', 'Disponible', 'ACTIVO', '2022-01-20 04:43:21', '2022-01-20 04:43:21');

SELECT * FROM COMPUTADOR;

/* =========== EMPLEADOS =========== */

INSERT INTO `empleado` (`ID_EMPLEADO`, `ID_EMPRESA_FK`, `NOMBRE_COMPLETO_EMPLEADO`, `CORREO_EMPLEADO`, `TIPO_DOCUMENTO_EMPLEADO`, `NUMERO_DOCUMENTO_EMPLEADO`, `FECHA_NACIMIENTO_EMPLEADO`, `NUMERO_CELULAR_EMPLEADO`, `NUMERO_FIJO_EMPLEADO`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, '1', 'Martha Leonor Espitia Garcia', 'martha@gmail.com', 'CC', '1212346534', '2003-07-27', '1233425468', NULL, 'ACTIVO', '2021-12-30 00:00:00', '2021-12-30 00:00:00'),
(NULL, '3', 'Frank Llanos Diaz', 'franlladiaz@gmail.com', 'CC', '1810965804', '2000-04-06', '3156478348', '523333', 'ACTIVO', '2022-01-10 14:17:17', '2022-01-10 14:17:17');
INSERT INTO `empleado` (`ID_EMPLEADO`, `ID_EMPRESA_FK`, `NOMBRE_COMPLETO_EMPLEADO`, `CORREO_EMPLEADO`, `TIPO_DOCUMENTO_EMPLEADO`, `NUMERO_DOCUMENTO_EMPLEADO`, `FECHA_NACIMIENTO_EMPLEADO`, `NUMERO_CELULAR_EMPLEADO`, `NUMERO_FIJO_EMPLEADO`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, '3', 'Simon Alexander Orosco', 'sialosrco@gmail.com', 'TI', '1000693694', '1998-07-15', '3209670459', '2096700', 'ACTIVO', '2022-01-19 21:11:23.000000', '2022-01-19 21:11:23.000000');
INSERT INTO `empleado` (`ID_EMPLEADO`, `ID_EMPRESA_FK`, `NOMBRE_COMPLETO_EMPLEADO`, `CORREO_EMPLEADO`, `TIPO_DOCUMENTO_EMPLEADO`, `NUMERO_DOCUMENTO_EMPLEADO`, `FECHA_NACIMIENTO_EMPLEADO`, `NUMERO_CELULAR_EMPLEADO`, `NUMERO_FIJO_EMPLEADO`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, '1', 'Luis Ocampos Almendrales', 'luisoc@gmail.com', 'CC', '1019', '0000-00-00', '3124456690', '244566', 'ACTIVO', '2022-01-20 03:48:15', '2022-01-20 03:48:15');
INSERT INTO `empleado` (`ID_EMPLEADO`, `ID_EMPRESA_FK`, `NOMBRE_COMPLETO_EMPLEADO`, `CORREO_EMPLEADO`, `TIPO_DOCUMENTO_EMPLEADO`, `NUMERO_DOCUMENTO_EMPLEADO`, `FECHA_NACIMIENTO_EMPLEADO`, `NUMERO_CELULAR_EMPLEADO`, `NUMERO_FIJO_EMPLEADO`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, '3', 'Willy Diaz Ampelo', 'willyd@gmail.com', 'CE', '1919867845', '1999-07-20', '3155867845', '5558678', 'ACTIVO', '2022-01-20 04:34:48', '2022-01-20 04:34:48');

/* =========== PRESTAMOS =========== */

INSERT INTO PRESTAMO (ID_EMPLEADO_FK, ID_PC_FK, FECHA_INICIO_PRESTAMO, FECHA_FIN_PRESTAMO, ESTADO,  CREATED_AT, UPDATED_AT)VALUES ('1', '1', '2022-01-07', '2022-01-21', 'ACTIVO', '2022-01-06 00:00:00', '2022-01-06 00:00:00');
INSERT INTO `prestamo` (`ID_PRESTAMO`, `ID_EMPLEADO_FK`, `ID_PC_FK`, `FECHA_INICIO_PRESTAMO`, `FECHA_FIN_PRESTAMO`, `ESTADO`, `CREATED_AT`, `UPDATED_AT`) VALUES (NULL, '4', '4', '2022-01-20 16:53:00', '2022-02-05 16:53:00', 'ACTIVO', '2022-01-20 04:56:27', '2022-01-20 04:56:27');

SELECT ID_PC,MODELO_PC FROM COMPUTADOR WHERE DISPONIBILIDAD_PC LIKE 'DISPONIBLE';

/* =========== PRUEBA DE SENTENCIAS MULTITABLA Y ACTIVAS =========== */

SELECT EMPLEADO.ID_EMPLEADO, EMPRESA.RAZON_SOCIAL_EMPRESA, EMPLEADO.NOMBRE_COMPLETO_EMPLEADO, EMPLEADO.CORREO_EMPLEADO , EMPLEADO.TIPO_DOCUMENTO_EMPLEADO, EMPLEADO.NUMERO_DOCUMENTO_EMPLEADO , EMPLEADO.FECHA_NACIMIENTO_EMPLEADO , EMPLEADO.NUMERO_CELULAR_EMPLEADO , EMPLEADO.NUMERO_FIJO_EMPLEADO , EMPLEADO.ESTADO , EMPLEADO.CREATED_AT , EMPLEADO.UPDATED_AT 
FROM EMPLEADO INNER JOIN EMPRESA
ON EMPLEADO.ID_EMPRESA_FK=EMPRESA.ID_EMPRESA
WHERE EMPLEADO.ESTADO = 'ACTIVO' ;

SELECT PRESTAMO.ID_PRESTAMO ,EMPLEADO.NOMBRE_COMPLETO_EMPLEADO ,COMPUTADOR.SERIAL_PC ,PRESTAMO.FECHA_INICIO_PRESTAMO ,PRESTAMO.FECHA_FIN_PRESTAMO ,PRESTAMO.ESTADO ,PRESTAMO.CREATED_AT ,PRESTAMO.UPDATED_AT 
FROM PRESTAMO INNER JOIN EMPLEADO
ON PRESTAMO.ID_EMPLEADO_FK=EMPLEADO.ID_EMPLEADO
INNER JOIN COMPUTADOR
ON PRESTAMO.ID_PC_FK=COMPUTADOR.ID_PC
WHERE PRESTAMO.ESTADO = 'ACTIVO' ;